// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/key_value.proto

package key_value_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Key_Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val           int64                  `protobuf:"varint,2,opt,name=Val,proto3" json:"Val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key_Value) Reset() {
	*x = Key_Value{}
	mi := &file_proto_key_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key_Value) ProtoMessage() {}

func (x *Key_Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_key_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key_Value.ProtoReflect.Descriptor instead.
func (*Key_Value) Descriptor() ([]byte, []int) {
	return file_proto_key_value_proto_rawDescGZIP(), []int{0}
}

func (x *Key_Value) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Key_Value) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int64                  `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_proto_key_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_proto_key_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_proto_key_value_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_key_value_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_key_value_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_key_value_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Value_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Val           int64                  `protobuf:"varint,2,opt,name=Val,proto3" json:"Val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value_Response) Reset() {
	*x = Value_Response{}
	mi := &file_proto_key_value_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Response) ProtoMessage() {}

func (x *Value_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_key_value_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Response.ProtoReflect.Descriptor instead.
func (*Value_Response) Descriptor() ([]byte, []int) {
	return file_proto_key_value_proto_rawDescGZIP(), []int{3}
}

func (x *Value_Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Value_Response) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

var File_proto_key_value_proto protoreflect.FileDescriptor

const file_proto_key_value_proto_rawDesc = "" +
	"\n" +
	"\x15proto/key_value.proto\x12\x0fkey_value_proto\"/\n" +
	"\tKey_Value\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\x03R\x03Key\x12\x10\n" +
	"\x03Val\x18\x02 \x01(\x03R\x03Val\"\x17\n" +
	"\x03Key\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\x03R\x03Key\"$\n" +
	"\bResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\"<\n" +
	"\x0eValue_Response\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x10\n" +
	"\x03Val\x18\x02 \x01(\x03R\x03Val2\x97\x02\n" +
	"\x11key_value_service\x12A\n" +
	"\x06create\x12\x1a.key_value_proto.Key_Value\x1a\x19.key_value_proto.Response\"\x00\x12A\n" +
	"\x06update\x12\x1a.key_value_proto.Key_Value\x1a\x19.key_value_proto.Response\"\x00\x12?\n" +
	"\x04read\x12\x14.key_value_proto.Key\x1a\x1f.key_value_proto.Value_Response\"\x00\x12;\n" +
	"\x06delete\x12\x14.key_value_proto.Key\x1a\x19.key_value_proto.Response\"\x00B8Z6github.com/Mohammed-Shammout/key_value/key_value_protob\x06proto3"

var (
	file_proto_key_value_proto_rawDescOnce sync.Once
	file_proto_key_value_proto_rawDescData []byte
)

func file_proto_key_value_proto_rawDescGZIP() []byte {
	file_proto_key_value_proto_rawDescOnce.Do(func() {
		file_proto_key_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_key_value_proto_rawDesc), len(file_proto_key_value_proto_rawDesc)))
	})
	return file_proto_key_value_proto_rawDescData
}

var file_proto_key_value_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_key_value_proto_goTypes = []any{
	(*Key_Value)(nil),      // 0: key_value_proto.Key_Value
	(*Key)(nil),            // 1: key_value_proto.Key
	(*Response)(nil),       // 2: key_value_proto.Response
	(*Value_Response)(nil), // 3: key_value_proto.Value_Response
}
var file_proto_key_value_proto_depIdxs = []int32{
	0, // 0: key_value_proto.key_value_service.create:input_type -> key_value_proto.Key_Value
	0, // 1: key_value_proto.key_value_service.update:input_type -> key_value_proto.Key_Value
	1, // 2: key_value_proto.key_value_service.read:input_type -> key_value_proto.Key
	1, // 3: key_value_proto.key_value_service.delete:input_type -> key_value_proto.Key
	2, // 4: key_value_proto.key_value_service.create:output_type -> key_value_proto.Response
	2, // 5: key_value_proto.key_value_service.update:output_type -> key_value_proto.Response
	3, // 6: key_value_proto.key_value_service.read:output_type -> key_value_proto.Value_Response
	2, // 7: key_value_proto.key_value_service.delete:output_type -> key_value_proto.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_key_value_proto_init() }
func file_proto_key_value_proto_init() {
	if File_proto_key_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_key_value_proto_rawDesc), len(file_proto_key_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_key_value_proto_goTypes,
		DependencyIndexes: file_proto_key_value_proto_depIdxs,
		MessageInfos:      file_proto_key_value_proto_msgTypes,
	}.Build()
	File_proto_key_value_proto = out.File
	file_proto_key_value_proto_goTypes = nil
	file_proto_key_value_proto_depIdxs = nil
}
